import type { ShapeRegistry } from '../shape-registry.ts';
import { registerAndroidHandlers } from './android/index.ts';
import { registerArchimateHandlers } from './archimate/index.ts';
import { registerArchimate3Handlers } from './archimate3/index.ts';
import { registerArrows2Handlers } from './arrows2/index.ts';
import { registerAtlassianHandlers } from './atlassian/index.ts';
import { registerAws3dHandlers } from './aws3d/index.ts';
import { registerAws4Handlers } from './aws4/index.ts';
import { registerBasicHandlers } from './basic/index.ts';
import { registerBootstrapHandlers } from './bootstrap/index.ts';
import { registerBpmnHandlers } from './bpmn/index.ts';
import { registerC4Handlers } from './c4/index.ts';
import { registerCabinetsHandlers } from './cabinets/index.ts';
import { registerCisco19Handlers } from './cisco19/index.ts';
import { registerCiscoSafeHandlers } from './cisco-safe/index.ts';
import { registerCoreHandlers } from './core/index.ts';
import { FallbackShapeHandler } from './core/fallback.ts';
import { registerDfdHandlers } from './dfd/index.ts';
import { registerEipHandlers } from './eip/index.ts';
import { registerElectricalHandlers } from './electrical/index.ts';
import { registerErHandlers } from './er/index.ts';
import { registerFloorplanHandlers } from './floorplan/index.ts';
import { registerFlowchartHandlers } from './flowchart/index.ts';
import { registerGcp2Handlers } from './gcp2/index.ts';
import { registerGmdlHandlers } from './gmdl/index.ts';
import { registerIbmHandlers } from './ibm/index.ts';
import { registerInfographicHandlers } from './infographic/index.ts';
import { registerIosHandlers } from './ios/index.ts';
import { registerIos7Handlers } from './ios7/index.ts';
import { registerIos7uiHandlers } from './ios7ui/index.ts';
import { registerKubernetesHandlers } from './kubernetes/index.ts';
import { registerLeanMappingHandlers } from './lean-mapping/index.ts';
import { registerMiscHandlers } from './misc/index.ts';
import { registerMockupHandlers } from './mockup/index.ts';
import { registerNetworksHandlers } from './networks/index.ts';
import { registerNetworks2Handlers } from './networks2/index.ts';
import { registerPid2instHandlers } from './pid2inst/index.ts';
import { registerPid2MiscHandlers } from './pid2misc/index.ts';
import { registerPid2ValvesHandlers } from './pid2valves/index.ts';
import { registerRackGeneralHandlers } from './rackGeneral/index.ts';
import { registerRackGeneralHandlers as registerRackGeneralHandlers2 } from './rack-general/index.ts';
import { registerSapHandlers } from './sap/index.ts';
import { registerSpecialHandlers } from './special/index.ts';
import { registerSwimlaneHandlers } from './swimlane/index.ts';
import { registerSysmlHandlers } from './sysml/index.ts';
import { registerTableHandlers } from './tables/index.ts';
import { registerUml25Handlers } from './uml25/index.ts';

export function registerHandlers(registry: ShapeRegistry): void {
  registry.setDefault(FallbackShapeHandler);
  
  // Register all shape handlers alphabetically
  registerAndroidHandlers(registry);
  registerArchimateHandlers(registry);
  registerArchimate3Handlers(registry);
  registerArrows2Handlers(registry);
  registerAtlassianHandlers(registry);
  registerAws3dHandlers(registry);
  registerAws4Handlers(registry);
  registerBasicHandlers(registry);
  registerBootstrapHandlers(registry);
  registerBpmnHandlers(registry);
  registerC4Handlers(registry);
  registerCabinetsHandlers(registry);
  registerCisco19Handlers(registry);
  registerCiscoSafeHandlers(registry);
  registerCoreHandlers(registry);
  registerDfdHandlers(registry);
  registerEipHandlers(registry);
  registerElectricalHandlers(registry);
  registerErHandlers(registry);
  registerFloorplanHandlers(registry);
  registerFlowchartHandlers(registry);
  registerGcp2Handlers(registry);
  registerGmdlHandlers(registry);
  registerIbmHandlers(registry);
  registerInfographicHandlers(registry);
  registerIosHandlers(registry);
  registerIos7Handlers(registry);
  registerIos7uiHandlers(registry);
  registerKubernetesHandlers(registry);
  registerLeanMappingHandlers(registry);
  registerMiscHandlers(registry);
  registerMockupHandlers(registry);
  registerNetworksHandlers(registry);
  registerNetworks2Handlers(registry);
  registerPid2instHandlers(registry);
  registerPid2MiscHandlers(registry);
  registerPid2ValvesHandlers(registry);
  registerRackGeneralHandlers(registry);
  registerRackGeneralHandlers2(registry);
  registerSapHandlers(registry);
  registerSpecialHandlers(registry);
  registerSwimlaneHandlers(registry);
  registerSysmlHandlers(registry);
  registerTableHandlers(registry);
  registerUml25Handlers(registry);
}
