import type { ShapeRegistry } from '../../shape-registry.ts';
import { SysmlPackageHandler } from './package.ts';
import { SysmlItemFlowHandler } from './item-flow.ts';
import { SysmlAccEventHandler } from './acc-event.ts';
import { SysmlActFinalHandler } from './act-final.ts';
import { SysmlActParamNodeHandler } from './act-param-node.ts';
import { SysmlCallBehActHandler } from './call-beh-act.ts';
import { SysmlFlowFinalHandler } from './flow-final.ts';
import { SysmlIsControlHandler } from './is-control.ts';
import { SysmlItemFlowLeftHandler } from './item-flow-left.ts';
import { SysmlItemFlowRightHandler } from './item-flow-right.ts';
import { SysmlObjFlowLHandler } from './obj-flow-l.ts';
import { SysmlObjFlowRHandler } from './obj-flow-r.ts';
import { SysmlParamDgmHandler } from './param-dgm.ts';
import { SysmlPort1Handler } from './port1.ts';
import { SysmlActPartHandler } from './act-part.ts';
import { SysmlActProbHandler } from './act-prob.ts';
import { SysmlCompStateHandler } from './comp-state.ts';
import { SysmlConsPropHandler } from './cons-prop.ts';
import { SysmlContHandler } from './cont.ts';
import { SysmlContOperHandler } from './cont-oper.ts';
import { SysmlCoregionHandler } from './coregion.ts';
import { SysmlDimensionHandler } from './dimension.ts';
import { SysmlIsActStreamHandler } from './is-act-stream.ts';
import { SysmlIsStreamHandler } from './is-stream.ts';
import { SysmlNestedPortHandler } from './nested-port.ts';
import { SysmlNoneHandler } from './none.ts';
import { SysmlPackage2Handler } from './package2.ts';
import { SysmlParamActSetHandler } from './param-act-set.ts';
import { SysmlParamSetHandler } from './param-set.ts';
import { SysmlPortHandler } from './port.ts';
import { SysmlPort2Handler } from './port2.ts';
import { SysmlPort3Handler } from './port3.ts';
import { SysmlPort4Handler } from './port4.ts';
import { SysmlProbabilityHandler } from './probability.ts';
import { SysmlRectHandler } from './rect.ts';
import { SysmlRegionHandler } from './region.ts';
import { SysmlSendSigActHandler } from './send-sig-act.ts';
import { SysmlSimpleStateHandler } from './simple-state.ts';
import { SysmlStateMachineHandler } from './state-machine.ts';
import { SysmlSubmStateHandler } from './subm-state.ts';
import { SysmlTimeEventHandler } from './time-event.ts';
import { SysmlUseCaseExtPtHandler } from './use-case-ext-pt.ts';
import { SysmlXHandler } from './x.ts';
import { SysmlCompositeHandler } from './composite.ts';

export function registerSysmlHandlers(registry: ShapeRegistry): void {
  registry.register('mxgraph.sysml.package', SysmlPackageHandler);
  registry.register('mxgraph.sysml.itemFlow', SysmlItemFlowHandler);
  registry.register('mxgraph.sysml.accEvent', SysmlAccEventHandler);
  registry.register('mxgraph.sysml.actFinal', SysmlActFinalHandler);
  registry.register('mxgraph.sysml.actParamNode', SysmlActParamNodeHandler);
  registry.register('mxgraph.sysml.callBehAct', SysmlCallBehActHandler);
  registry.register('mxgraph.sysml.flowFinal', SysmlFlowFinalHandler);
  registry.register('mxgraph.sysml.isControl', SysmlIsControlHandler);
  registry.register('mxgraph.sysml.itemFlowLeft', SysmlItemFlowLeftHandler);
  registry.register('mxgraph.sysml.itemFlowRight', SysmlItemFlowRightHandler);
  registry.register('mxgraph.sysml.objFlowL', SysmlObjFlowLHandler);
  registry.register('mxgraph.sysml.objFlowR', SysmlObjFlowRHandler);
  registry.register('mxgraph.sysml.paramDgm', SysmlParamDgmHandler);
  registry.register('mxgraph.sysml.port1', SysmlPort1Handler);
  registry.register('mxgraph.sysml.actPart', SysmlActPartHandler);
  registry.register('mxgraph.sysml.actProb', SysmlActProbHandler);
  registry.register('mxgraph.sysml.compState', SysmlCompStateHandler);
  registry.register('mxgraph.sysml.consProp', SysmlConsPropHandler);
  registry.register('mxgraph.sysml.cont', SysmlContHandler);
  registry.register('mxgraph.sysml.contOper', SysmlContOperHandler);
  registry.register('mxgraph.sysml.coregion', SysmlCoregionHandler);
  registry.register('mxgraph.sysml.dimension', SysmlDimensionHandler);
  registry.register('mxgraph.sysml.isActStream', SysmlIsActStreamHandler);
  registry.register('mxgraph.sysml.isStream', SysmlIsStreamHandler);
  registry.register('mxgraph.sysml.nestedPort', SysmlNestedPortHandler);
  registry.register('mxgraph.sysml.none', SysmlNoneHandler);
  registry.register('mxgraph.sysml.package2', SysmlPackage2Handler);
  registry.register('mxgraph.sysml.paramActSet', SysmlParamActSetHandler);
  registry.register('mxgraph.sysml.paramSet', SysmlParamSetHandler);
  registry.register('mxgraph.sysml.port', SysmlPortHandler);
  registry.register('mxgraph.sysml.port2', SysmlPort2Handler);
  registry.register('mxgraph.sysml.port3', SysmlPort3Handler);
  registry.register('mxgraph.sysml.port4', SysmlPort4Handler);
  registry.register('mxgraph.sysml.probability', SysmlProbabilityHandler);
  registry.register('mxgraph.sysml.rect', SysmlRectHandler);
  registry.register('mxgraph.sysml.region', SysmlRegionHandler);
  registry.register('mxgraph.sysml.sendSigAct', SysmlSendSigActHandler);
  registry.register('mxgraph.sysml.simpleState', SysmlSimpleStateHandler);
  registry.register('mxgraph.sysml.stateMachine', SysmlStateMachineHandler);
  registry.register('mxgraph.sysml.submState', SysmlSubmStateHandler);
  registry.register('mxgraph.sysml.composite', SysmlCompositeHandler);
  registry.register('mxgraph.sysml.timeEvent', SysmlTimeEventHandler);
  registry.register('mxgraph.sysml.useCaseExtPt', SysmlUseCaseExtPtHandler);
  registry.register('mxgraph.sysml.x', SysmlXHandler);
}
