import type { ShapeRegistry } from '../../shape-registry.ts';
import { Aws3dAmiHandler } from './ami.ts';
import { Aws3dAmi2Handler } from './ami2.ts';
import { Aws3dApplicationHandler } from './application.ts';
import { Aws3dApplication2Handler } from './application2.ts';
import { Aws3dApplicationServerHandler } from './application-server.ts';
import { Aws3dArrowNEHandler } from './arrow-ne.ts';
import { Aws3dArrowNWHandler } from './arrow-nw.ts';
import { Aws3dArrowSEHandler } from './arrow-se.ts';
import { Aws3dArrowSWHandler } from './arrow-sw.ts';
import { Aws3dArrowlessNEHandler } from './arrowless-ne.ts';
import { Aws3dCloudfrontHandler } from './cloudfront.ts';
import { Aws3dCustomerGatewayHandler } from './customer-gateway.ts';
import { Aws3dDashedArrowlessEdgeHandler } from './dashed-arrowless-edge.ts';
import { Aws3dDashedArrowlessEdge2Handler } from './dashed-arrowless-edge2.ts';
import { Aws3dDashedEdgeHandler } from './dashed-edge.ts';
import { Aws3dDashedEdge2Handler } from './dashed-edge2.ts';
import { Aws3dDashedEdgeDoubleHandler } from './dashed-edge-double.ts';
import { Aws3dDashedEdgeDouble2Handler } from './dashed-edge-double2.ts';
import { Aws3dDataCenterHandler } from './data-center.ts';
import { Aws3dDataServerHandler } from './data-server.ts';
import { Aws3dDeciderHandler } from './decider.ts';
import { Aws3dDynamoDbHandler } from './dynamo-db.ts';
import { Aws3dEbsHandler } from './ebs.ts';
import { Aws3dEbs2Handler } from './ebs2.ts';
import { Aws3dElasticBeanstalkHandler } from './elastic-beanstalk.ts';
import { Aws3dElasticLoadBalancingHandler } from './elastic-load-balancing.ts';
import { Aws3dElasticMapReduceHandler } from './elastic-map-reduce.ts';
import { Aws3dEmailServiceHandler } from './email-service.ts';
import { Aws3dFlatDoubleEdgeHandler } from './flat-double-edge.ts';
import { Aws3dFlatDoubleEdge2Handler } from './flat-double-edge2.ts';
import { Aws3dFlatEdgeHandler } from './flat-edge.ts';
import { Aws3dFlatEdge2Handler } from './flat-edge2.ts';
import { Aws3dGlacierHandler } from './glacier.ts';
import { Aws3dInstanceHandler } from './instance.ts';
import { Aws3dInternetGatewayHandler } from './internet-gateway.ts';
import { Aws3dLambdaHandler } from './lambda.ts';
import { Aws3dOracleDataCenterHandler } from './oracle-data-center.ts';
import { Aws3dOracleDbServerHandler } from './oracle-db-server.ts';
import { Aws3dOracleServerHandler } from './oracle-server.ts';
import { Aws3dRdsHandler } from './rds.ts';
import { Aws3dRdsMasterHandler } from './rds-master.ts';
import { Aws3dRdsSlaveHandler } from './rds-slave.ts';
import { Aws3dRedshiftHandler } from './redshift.ts';
import { Aws3dRoute53Handler } from './route53.ts';
import { Aws3dS3Handler } from './s3.ts';
import { Aws3dS3BucketHandler } from './s3bucket.ts';
import { Aws3dSearchEngineHandler } from './search-engine.ts';
import { Aws3dSecureConnectionHandler } from './secure-connection.ts';
import { Aws3dSecurityTokenServiceHandler } from './security-token-service.ts';
import { Aws3dSimpleDbHandler } from './simple-db.ts';
import { Aws3dSimpleDb2Handler } from './simple-db2.ts';
import { Aws3dSnapshotHandler } from './snapshot.ts';
import { Aws3dSqsHandler } from './sqs.ts';
import { Aws3dVpcGatewayHandler } from './vpc-gateway.ts';
import { Aws3dWebServerHandler } from './web-server.ts';
import { Aws3dWorkerHandler } from './worker.ts';
import { Aws3dWorkflowServiceHandler } from './workflow-service.ts';

export const registerAws3dHandlers = (registry: ShapeRegistry): void => {
  registry.register('mxgraph.aws3d.ami', Aws3dAmiHandler);
  registry.register('mxgraph.aws3d.ami2', Aws3dAmi2Handler);
  registry.register('mxgraph.aws3d.application', Aws3dApplicationHandler);
  registry.register('mxgraph.aws3d.application2', Aws3dApplication2Handler);
  registry.register('mxgraph.aws3d.application_server', Aws3dApplicationServerHandler);
  registry.register('mxgraph.aws3d.arrowNE', Aws3dArrowNEHandler);
  registry.register('mxgraph.aws3d.arrowNW', Aws3dArrowNWHandler);
  registry.register('mxgraph.aws3d.arrowSE', Aws3dArrowSEHandler);
  registry.register('mxgraph.aws3d.arrowSW', Aws3dArrowSWHandler);
  registry.register('mxgraph.aws3d.arrowlessNE', Aws3dArrowlessNEHandler);
  registry.register('mxgraph.aws3d.cloudfront', Aws3dCloudfrontHandler);
  registry.register('mxgraph.aws3d.customerGateway', Aws3dCustomerGatewayHandler);
  registry.register('mxgraph.aws3d.dashedArrowlessEdge', Aws3dDashedArrowlessEdgeHandler);
  registry.register('mxgraph.aws3d.dashedArrowlessEdge2', Aws3dDashedArrowlessEdge2Handler);
  registry.register('mxgraph.aws3d.dashedEdge', Aws3dDashedEdgeHandler);
  registry.register('mxgraph.aws3d.dashedEdge2', Aws3dDashedEdge2Handler);
  registry.register('mxgraph.aws3d.dashedEdgeDouble', Aws3dDashedEdgeDoubleHandler);
  registry.register('mxgraph.aws3d.dashedEdgeDouble2', Aws3dDashedEdgeDouble2Handler);
  registry.register('mxgraph.aws3d.dataCenter', Aws3dDataCenterHandler);
  registry.register('mxgraph.aws3d.dataServer', Aws3dDataServerHandler);
  registry.register('mxgraph.aws3d.decider', Aws3dDeciderHandler);
  registry.register('mxgraph.aws3d.dynamoDb', Aws3dDynamoDbHandler);
  registry.register('mxgraph.aws3d.ebs', Aws3dEbsHandler);
  registry.register('mxgraph.aws3d.ebs2', Aws3dEbs2Handler);
  registry.register('mxgraph.aws3d.elasticBeanstalk', Aws3dElasticBeanstalkHandler);
  registry.register('mxgraph.aws3d.elasticLoadBalancing', Aws3dElasticLoadBalancingHandler);
  registry.register('mxgraph.aws3d.elasticMapReduce', Aws3dElasticMapReduceHandler);
  registry.register('mxgraph.aws3d.email_service', Aws3dEmailServiceHandler);
  registry.register('mxgraph.aws3d.flatDoubleEdge', Aws3dFlatDoubleEdgeHandler);
  registry.register('mxgraph.aws3d.flatDoubleEdge2', Aws3dFlatDoubleEdge2Handler);
  registry.register('mxgraph.aws3d.flatEdge', Aws3dFlatEdgeHandler);
  registry.register('mxgraph.aws3d.flatEdge2', Aws3dFlatEdge2Handler);
  registry.register('mxgraph.aws3d.glacier', Aws3dGlacierHandler);
  registry.register('mxgraph.aws3d.instance', Aws3dInstanceHandler);
  registry.register('mxgraph.aws3d.internetGateway', Aws3dInternetGatewayHandler);
  registry.register('mxgraph.aws3d.lambda', Aws3dLambdaHandler);
  registry.register('mxgraph.aws3d.oracleDataCenter', Aws3dOracleDataCenterHandler);
  registry.register('mxgraph.aws3d.oracleDbServer', Aws3dOracleDbServerHandler);
  registry.register('mxgraph.aws3d.oracleServer', Aws3dOracleServerHandler);
  registry.register('mxgraph.aws3d.rds', Aws3dRdsHandler);
  registry.register('mxgraph.aws3d.rdsMaster', Aws3dRdsMasterHandler);
  registry.register('mxgraph.aws3d.rdsSlave', Aws3dRdsSlaveHandler);
  registry.register('mxgraph.aws3d.redshift', Aws3dRedshiftHandler);
  registry.register('mxgraph.aws3d.route53', Aws3dRoute53Handler);
  registry.register('mxgraph.aws3d.s3', Aws3dS3Handler);
  registry.register('mxgraph.aws3d.s3Bucket', Aws3dS3BucketHandler);
  registry.register('mxgraph.aws3d.searchEngine', Aws3dSearchEngineHandler);
  registry.register('mxgraph.aws3d.secureConnection', Aws3dSecureConnectionHandler);
  registry.register('mxgraph.aws3d.securityTokenService', Aws3dSecurityTokenServiceHandler);
  registry.register('mxgraph.aws3d.simpleDb', Aws3dSimpleDbHandler);
  registry.register('mxgraph.aws3d.simpleDb2', Aws3dSimpleDb2Handler);
  registry.register('mxgraph.aws3d.snapshot', Aws3dSnapshotHandler);
  registry.register('mxgraph.aws3d.sqs', Aws3dSqsHandler);
  registry.register('mxgraph.aws3d.vpcGateway', Aws3dVpcGatewayHandler);
  registry.register('mxgraph.aws3d.webServer', Aws3dWebServerHandler);
  registry.register('mxgraph.aws3d.worker', Aws3dWorkerHandler);
  registry.register('mxgraph.aws3d.workflowService', Aws3dWorkflowServiceHandler);
};
