import type { ShapeRegistry } from '../../shape-registry.ts';
import { FloorplanDoorDoubleHandler } from './door-double.ts';
import { FloorplanDoorLeftHandler } from './door-left.ts';
import { FloorplanDoorRightHandler } from './door-right.ts';
import { FloorplanRoomHandler } from './room.ts';
import { FloorplanStairsHandler } from './stairs.ts';
import { FloorplanStairsRestHandler } from './stairs-rest.ts';
import { FloorplanWallCornerHandler } from './wall-corner.ts';
import { FloorplanWallHandler } from './wall.ts';
import { FloorplanWallUHandler } from './wall-u.ts';
import { FloorplanWindowHandler } from './window.ts';
import { FloorplanDimensionHandler } from './dimension.ts';
import { FloorplanDimensionBottomHandler } from './dimension-bottom.ts';
import { FloorplanDoorAccordionHandler } from './door-accordion.ts';
import { FloorplanDoorBifoldHandler } from './door-bifold.ts';
import { FloorplanDoorBypassHandler } from './door-bypass.ts';
import { FloorplanDoorDoubleActionHandler } from './door-double-action.ts';
import { FloorplanDoorDoublePocketHandler } from './door-double-pocket.ts';
import { FloorplanDoorOpposingHandler } from './door-opposing.ts';
import { FloorplanDoorOverheadHandler } from './door-overhead.ts';
import { FloorplanDoorPocketHandler } from './door-pocket.ts';
import { FloorplanDoorRevolvingHandler } from './door-revolving.ts';
import { FloorplanDoorSlidingGlassHandler } from './door-sliding-glass.ts';
import { FloorplanDoorUnevenHandler } from './door-uneven.ts';
import { FloorplanOpeningHandler } from './opening.ts';
import { FloorplanWindowBayHandler } from './window-bay.ts';
import { FloorplanWindowBowHandler } from './window-bow.ts';
import { FloorplanWindowGardenHandler } from './window-garden.ts';
import { FloorplanWindowGliderHandler } from './window-glider.ts';

export function registerFloorplanHandlers(registry: ShapeRegistry): void {
  registry.register('mxgraph.floorplan.doorRight', FloorplanDoorRightHandler);
  registry.register('mxgraph.floorplan.doorLeft', FloorplanDoorLeftHandler);
  registry.register('mxgraph.floorplan.doorDouble', FloorplanDoorDoubleHandler);
  registry.register('mxgraph.floorplan.window', FloorplanWindowHandler);
  registry.register('mxgraph.floorplan.room', FloorplanRoomHandler);
  registry.register('mxgraph.floorplan.stairs', FloorplanStairsHandler);
  registry.register('mxgraph.floorplan.stairsRest', FloorplanStairsRestHandler);
  registry.register('mxgraph.floorplan.wall', FloorplanWallHandler);
  registry.register('mxgraph.floorplan.wallCorner', FloorplanWallCornerHandler);
  registry.register('mxgraph.floorplan.wallU', FloorplanWallUHandler);
  registry.register('mxgraph.floorplan.dimension', FloorplanDimensionHandler);
  registry.register('mxgraph.floorplan.dimensionBottom', FloorplanDimensionBottomHandler);
  registry.register('mxgraph.floorplan.doorAccordion', FloorplanDoorAccordionHandler);
  registry.register('mxgraph.floorplan.doorBifold', FloorplanDoorBifoldHandler);
  registry.register('mxgraph.floorplan.doorBypass', FloorplanDoorBypassHandler);
  registry.register('mxgraph.floorplan.doorDoubleAction', FloorplanDoorDoubleActionHandler);
  registry.register('mxgraph.floorplan.doorDoublePocket', FloorplanDoorDoublePocketHandler);
  registry.register('mxgraph.floorplan.doorOpposing', FloorplanDoorOpposingHandler);
  registry.register('mxgraph.floorplan.doorOverhead', FloorplanDoorOverheadHandler);
  registry.register('mxgraph.floorplan.doorPocket', FloorplanDoorPocketHandler);
  registry.register('mxgraph.floorplan.doorRevolving', FloorplanDoorRevolvingHandler);
  registry.register('mxgraph.floorplan.doorSlidingGlass', FloorplanDoorSlidingGlassHandler);
  registry.register('mxgraph.floorplan.doorUneven', FloorplanDoorUnevenHandler);
  registry.register('mxgraph.floorplan.opening', FloorplanOpeningHandler);
  registry.register('mxgraph.floorplan.windowBay', FloorplanWindowBayHandler);
  registry.register('mxgraph.floorplan.windowBow', FloorplanWindowBowHandler);
  registry.register('mxgraph.floorplan.windowGarden', FloorplanWindowGardenHandler);
  registry.register('mxgraph.floorplan.windowGlider', FloorplanWindowGliderHandler);
}