import type { ShapeRegistry } from '../../shape-registry.ts';
import { LeanMappingFifoLaneHandler } from './fifo-lane.ts';
import { LeanMappingManufacturingProcessHandler } from './manufacturing-process.ts';
import { LeanMappingOutsideSourcesHandler } from './outside-sources.ts';
import { LeanMappingPushArrowHandler } from './push-arrow.ts';
import { LeanMappingScheduleHandler } from './schedule.ts';
import { LeanMappingTruckShipmentHandler } from './truck-shipment.ts';
import { LeanMappingDataBoxHandler } from './data-box.ts';
import { LeanMappingInventoryBoxHandler } from './inventory-box.ts';
import { LeanMappingPhysicalPullHandler } from './physical-pull.ts';
import { LeanMappingTimeline2Handler } from './timeline2.ts';
import { LeanMappingTimelineHandler } from './timeline.ts';
import { LeanMappingBatchedKanbanHandler } from './batched-kanban.ts';
import { LeanMappingBoatShipmentHandler } from './boat-shipment.ts';
import { LeanMappingBufferOrSafetyStockHandler } from './buffer-or-safety-stock.ts';
import { LeanMappingControlCenterHandler } from './control-center.ts';
import { LeanMappingCrossDockHandler } from './cross-dock.ts';
import { LeanMappingFifoSequenceFlowHandler } from './fifo-sequence-flow.ts';
import { LeanMappingManufacturingProcessSharedHandler } from './manufacturing-process-shared.ts';
import { LeanMappingOrdersHandler } from './orders.ts';
import { LeanMappingProductionKanbanHandler } from './production-kanban.ts';
import { LeanMappingRailShipmentHandler } from './rail-shipment.ts';
import { LeanMappingSequencedPullBallHandler } from './sequenced-pull-ball.ts';
import { LeanMappingSignalKanbanHandler } from './signal-kanban.ts';
import { LeanMappingSupermarketHandler } from './supermarket.ts';
import { LeanMappingWarehouseHandler } from './warehouse.ts';
import { LeanMappingWithdrawalKanbanHandler } from './withdrawal-kanban.ts';
import { LeanMappingWorkCellHandler } from './work-cell.ts';
import { LeanMappingElectronicInfoFlowEdgeHandler } from './electronic-info-flow-edge.ts';
import { LeanMappingManualInfoFlowEdgeHandler } from './manual-info-flow-edge.ts';

export function registerLeanMappingHandlers(registry: ShapeRegistry): void {
  registry.register('mxgraph.lean_mapping.outside_sources', LeanMappingOutsideSourcesHandler);
  registry.register('mxgraph.lean_mapping.manufacturing_process', LeanMappingManufacturingProcessHandler);
  registry.register('mxgraph.lean_mapping.fifo_lane', LeanMappingFifoLaneHandler);
  registry.register('mxgraph.lean_mapping.truck_shipment', LeanMappingTruckShipmentHandler);
  registry.register('mxgraph.lean_mapping.schedule', LeanMappingScheduleHandler);
  registry.register('mxgraph.lean_mapping.push_arrow', LeanMappingPushArrowHandler);
  registry.register('mxgraph.lean_mapping.data_box', LeanMappingDataBoxHandler);
  registry.register('mxgraph.lean_mapping.inventory_box', LeanMappingInventoryBoxHandler);
  registry.register('mxgraph.lean_mapping.physical_pull', LeanMappingPhysicalPullHandler);
  registry.register('mxgraph.lean_mapping.timeline2', LeanMappingTimeline2Handler);
  registry.register('mxgraph.lean_mapping.timeline', LeanMappingTimelineHandler);
  registry.register('mxgraph.lean_mapping.batched_kanban', LeanMappingBatchedKanbanHandler);
  registry.register('mxgraph.lean_mapping.boat_shipment', LeanMappingBoatShipmentHandler);
  registry.register('mxgraph.lean_mapping.buffer_or_safety_stock', LeanMappingBufferOrSafetyStockHandler);
  registry.register('mxgraph.lean_mapping.control_center', LeanMappingControlCenterHandler);
  registry.register('mxgraph.lean_mapping.crossDock', LeanMappingCrossDockHandler);
  registry.register('mxgraph.lean_mapping.fifo_sequence_flow', LeanMappingFifoSequenceFlowHandler);
  registry.register('mxgraph.lean_mapping.manufacturing_process_shared', LeanMappingManufacturingProcessSharedHandler);
  registry.register('mxgraph.lean_mapping.orders', LeanMappingOrdersHandler);
  registry.register('mxgraph.lean_mapping.production_kanban', LeanMappingProductionKanbanHandler);
  registry.register('mxgraph.lean_mapping.rail_shipment', LeanMappingRailShipmentHandler);
  registry.register('mxgraph.lean_mapping.sequenced_pull_ball', LeanMappingSequencedPullBallHandler);
  registry.register('mxgraph.lean_mapping.signal_kanban', LeanMappingSignalKanbanHandler);
  registry.register('mxgraph.lean_mapping.supermarket', LeanMappingSupermarketHandler);
  registry.register('mxgraph.lean_mapping.warehouse', LeanMappingWarehouseHandler);
  registry.register('mxgraph.lean_mapping.withdrawal_kanban', LeanMappingWithdrawalKanbanHandler);
  registry.register('mxgraph.lean_mapping.work_cell', LeanMappingWorkCellHandler);
  registry.register('mxgraph.lean_mapping.electronic_info_flow_edge', LeanMappingElectronicInfoFlowEdgeHandler);
  registry.register('mxgraph.lean_mapping.manual_info_flow_edge', LeanMappingManualInfoFlowEdgeHandler);
}
