import type { ShapeRegistry } from '../../shape-registry.ts';
import { Archimate3ActorHandler } from './actor.ts';
import { Archimate3ApplicationHandler } from './application.ts';
import { Archimate3ServiceHandler } from './service.ts';
import { Archimate3TechHandler } from './tech.ts';
import { Archimate3ArtifactHandler } from './artifact.ts';
import { Archimate3AssessHandler } from './assess.ts';
import { Archimate3BusinessObjectHandler } from './business-object.ts';
import { Archimate3CapabilityHandler } from './capability.ts';
import { Archimate3CollaborationHandler } from './collaboration.ts';
import { Archimate3CommNetwHandler } from './comm-netw.ts';
import { Archimate3ComponentHandler } from './component.ts';
import { Archimate3ConstraintHandler } from './constraint.ts';
import { Archimate3ContractHandler } from './contract.ts';
import { Archimate3ContractSmallHandler } from './contract-small.ts';
import { Archimate3CourseHandler } from './course.ts';
import { Archimate3DeliverableHandler } from './deliverable.ts';
import { Archimate3DeviceHandler } from './device.ts';
import { Archimate3DistributionHandler } from './distribution.ts';
import { Archimate3DriverHandler } from './driver.ts';
import { Archimate3EquipmentHandler } from './equipment.ts';
import { Archimate3EventHandler } from './event.ts';
import { Archimate3Event2Handler } from './event2.ts';
import { Archimate3FacilityHandler } from './facility.ts';
import { Archimate3FunctionHandler } from './function.ts';
import { Archimate3GapHandler } from './gap.ts';
import { Archimate3GapIconHandler } from './gap-icon.ts';
import { Archimate3GoalHandler } from './goal.ts';
import { Archimate3GroupingHandler } from './grouping.ts';
import { Archimate3InteractionHandler } from './interaction.ts';
import { Archimate3InterfaceHandler } from './interface.ts';
import { Archimate3LocationHandler } from './location.ts';
import { Archimate3LocationIconHandler } from './location-icon.ts';
import { Archimate3MaterialHandler } from './material.ts';
import { Archimate3NetworkHandler } from './network.ts';
import { Archimate3NodeHandler } from './node.ts';
import { Archimate3OutcomeHandler } from './outcome.ts';
import { Archimate3PassiveHandler } from './passive.ts';
import { Archimate3PathHandler } from './path.ts';
import { Archimate3PlateauHandler } from './plateau.ts';
import { Archimate3PrincipleHandler } from './principle.ts';
import { Archimate3ProcessHandler } from './process.ts';
import { Archimate3ProductHandler } from './product.ts';
import { Archimate3ProductSmallHandler } from './product-small.ts';
import { Archimate3RepresentationHandler } from './representation.ts';
import { Archimate3RepresentationSmallHandler } from './representation-small.ts';
import { Archimate3RequirementHandler } from './requirement.ts';
import { Archimate3ResourceHandler } from './resource.ts';
import { Archimate3RoleHandler } from './role.ts';
import { Archimate3SysSwHandler } from './sys-sw.ts';
import { Archimate3ValueStreamHandler } from './value-stream.ts';
import { Archimate3WorkPackageHandler } from './work-package.ts';
import { Archimate3ValueHandler } from './value.ts';
import { Archimate3MeaningHandler } from './meaning.ts';

export function registerArchimate3Handlers(registry: ShapeRegistry): void {
  registry.register('mxgraph.archimate3.actor', Archimate3ActorHandler);
  registry.register('mxgraph.archimate3.tech', Archimate3TechHandler);
  registry.register('mxgraph.archimate3.application', Archimate3ApplicationHandler);
  registry.register('mxgraph.archimate3.service', Archimate3ServiceHandler);
  registry.register('mxgraph.archimate3.artifact', Archimate3ArtifactHandler);
  registry.register('mxgraph.archimate3.assess', Archimate3AssessHandler);
  registry.register('mxgraph.archimate3.businessObject', Archimate3BusinessObjectHandler);
  registry.register('mxgraph.archimate3.capability', Archimate3CapabilityHandler);
  registry.register('mxgraph.archimate3.collaboration', Archimate3CollaborationHandler);
  registry.register('mxgraph.archimate3.commNetw', Archimate3CommNetwHandler);
  registry.register('mxgraph.archimate3.component', Archimate3ComponentHandler);
  registry.register('mxgraph.archimate3.constraint', Archimate3ConstraintHandler);
  registry.register('mxgraph.archimate3.contract', Archimate3ContractHandler);
  registry.register('mxgraph.archimate3.contractSmall', Archimate3ContractSmallHandler);
  registry.register('mxgraph.archimate3.course', Archimate3CourseHandler);
  registry.register('mxgraph.archimate3.deliverable', Archimate3DeliverableHandler);
  registry.register('mxgraph.archimate3.device', Archimate3DeviceHandler);
  registry.register('mxgraph.archimate3.distribution', Archimate3DistributionHandler);
  registry.register('mxgraph.archimate3.driver', Archimate3DriverHandler);
  registry.register('mxgraph.archimate3.equipment', Archimate3EquipmentHandler);
  registry.register('mxgraph.archimate3.event', Archimate3EventHandler);
  registry.register('mxgraph.archimate3.event2', Archimate3Event2Handler);
  registry.register('mxgraph.archimate3.facility', Archimate3FacilityHandler);
  registry.register('mxgraph.archimate3.function', Archimate3FunctionHandler);
  registry.register('mxgraph.archimate3.gap', Archimate3GapHandler);
  registry.register('mxgraph.archimate3.gapIcon', Archimate3GapIconHandler);
  registry.register('mxgraph.archimate3.goal', Archimate3GoalHandler);
  registry.register('mxgraph.archimate3.grouping', Archimate3GroupingHandler);
  registry.register('mxgraph.archimate3.interaction', Archimate3InteractionHandler);
  registry.register('mxgraph.archimate3.interface', Archimate3InterfaceHandler);
  registry.register('mxgraph.archimate3.location', Archimate3LocationHandler);
  registry.register('mxgraph.archimate3.locationIcon', Archimate3LocationIconHandler);
  registry.register('mxgraph.archimate3.material', Archimate3MaterialHandler);
  registry.register('mxgraph.archimate3.network', Archimate3NetworkHandler);
  registry.register('mxgraph.archimate3.node', Archimate3NodeHandler);
  registry.register('mxgraph.archimate3.outcome', Archimate3OutcomeHandler);
  registry.register('mxgraph.archimate3.passive', Archimate3PassiveHandler);
  registry.register('mxgraph.archimate3.path', Archimate3PathHandler);
  registry.register('mxgraph.archimate3.plateau', Archimate3PlateauHandler);
  registry.register('mxgraph.archimate3.principle', Archimate3PrincipleHandler);
  registry.register('mxgraph.archimate3.process', Archimate3ProcessHandler);
  registry.register('mxgraph.archimate3.product', Archimate3ProductHandler);
  registry.register('mxgraph.archimate3.productSmall', Archimate3ProductSmallHandler);
  registry.register('mxgraph.archimate3.representation', Archimate3RepresentationHandler);
  registry.register('mxgraph.archimate3.representationSmall', Archimate3RepresentationSmallHandler);
  registry.register('mxgraph.archimate3.requirement', Archimate3RequirementHandler);
  registry.register('mxgraph.archimate3.resource', Archimate3ResourceHandler);
  registry.register('mxgraph.archimate3.role', Archimate3RoleHandler);
  registry.register('mxgraph.archimate3.sysSw', Archimate3SysSwHandler);
  registry.register('mxgraph.archimate3.valueStream', Archimate3ValueStreamHandler);
  registry.register('mxgraph.archimate3.workPackage', Archimate3WorkPackageHandler);
  registry.register('mxgraph.archimate3.value', Archimate3ValueHandler);
  registry.register('mxgraph.archimate3.meaning', Archimate3MeaningHandler);
}
