import type { ShapeRegistry } from '../../shape-registry.ts';
import { AssociativeEntityHandler } from './associative-entity.ts';
import { CalloutHandler } from './callout.ts';
import { CollateHandler } from './collate.ts';
import { CrossHandler } from './cross.ts';
import { CrossbarHandler } from './crossbar.ts';
import { CylinderHandler } from './cylinder.ts';
import { Cylinder2Handler } from './cylinder2.ts';
import { Cylinder3Handler } from './cylinder3.ts';
import { DataStorageHandler } from './data-storage.ts';
import { DatastoreHandler } from './datastore.ts';
import { DisplayHandler } from './display.ts';
import { DoubleArrowHandler } from './double-arrow.ts';
import { DoubleEllipseHandler } from './double-ellipse.ts';
import { EllipseHandler } from './ellipse.ts';
import { ExtHandler } from './ext.ts';
import { HexagonHandler } from './hexagon.ts';
import { InternalStorageHandler } from './internal-storage.ts';
import { IsoCubeHandler } from './iso-cube.ts';
import { IsoCube2Handler } from './iso-cube2.ts';
import { IsoRectangleHandler } from './iso-rectangle.ts';
import { LineEllipseHandler } from './line-ellipse.ts';
import { LollipopHandler } from './lollipop.ts';
import { LoopLimitHandler } from './loop-limit.ts';
import { MessageHandler } from './message.ts';
import { ModuleHandler } from './module.ts';
import { Note2Handler } from './note2.ts';
import { OrHandler } from './or.ts';
import { OrEllipseHandler } from './or-ellipse.ts';
import { ParallelMarkerHandler } from './parallel-marker.ts';
import { ParallelogramHandler } from './parallelogram.ts';
import { Process2Handler } from './process2.ts';
import { ProvidedRequiredInterfaceHandler } from './provided-required-interface.ts';
import { RectangleHandler } from './rectangle.ts';
import { RequiredInterfaceHandler } from './required-interface.ts';
import { RequiresHandler } from './requires.ts';
import { RhombusHandler } from './rhombus.ts';
import { SingleArrowHandler } from './single-arrow.ts';
import { SortShapeHandler } from './sort-shape.ts';
import { SumEllipseHandler } from './sum-ellipse.ts';
import { SwitchHandler } from './switch.ts';
import { TapeDataHandler } from './tape-data.ts';
import { TeeHandler } from './tee.ts';
import { TransparentHandler } from './transparent.ts';
import { TrapezoidHandler } from './trapezoid.ts';
import { TriangleHandler } from './triangle.ts';
import { UmlBoundaryHandler } from './uml-boundary.ts';
import { UmlControlHandler } from './uml-control.ts';
import { UmlDestroyHandler } from './uml-destroy.ts';
import { UmlEntityHandler } from './uml-entity.ts';
import { UmlStateHandler } from './uml-state.ts';
import { XorHandler } from './xor.ts';

export function registerCoreHandlers(registry: ShapeRegistry): void {
  registry.register('associativeEntity', AssociativeEntityHandler);
  registry.register('callout', CalloutHandler);
  registry.register('collate', CollateHandler);
  registry.register('cross', CrossHandler);
  registry.register('crossbar', CrossbarHandler);
  registry.register('cylinder', CylinderHandler);
  registry.register('cylinder2', Cylinder2Handler);
  registry.register('cylinder3', Cylinder3Handler);
  registry.register('dataStorage', DataStorageHandler);
  registry.register('datastore', DatastoreHandler);
  registry.register('display', DisplayHandler);
  registry.register('doubleArrow', DoubleArrowHandler);
  registry.register('doubleEllipse', DoubleEllipseHandler);
  registry.register('ellipse', EllipseHandler);
  registry.register('ext', ExtHandler);
  registry.register('hexagon', HexagonHandler);
  registry.register('internalStorage', InternalStorageHandler);
  registry.register('isoCube', IsoCubeHandler);
  registry.register('isoCube2', IsoCube2Handler);
  registry.register('isoRectangle', IsoRectangleHandler);
  registry.register('lineEllipse', LineEllipseHandler);
  registry.register('lollipop', LollipopHandler);
  registry.register('loopLimit', LoopLimitHandler);
  registry.register('message', MessageHandler);
  registry.register('module', ModuleHandler);
  registry.register('note2', Note2Handler);
  registry.register('or', OrHandler);
  registry.register('orEllipse', OrEllipseHandler);
  registry.register('parallelMarker', ParallelMarkerHandler);
  registry.register('parallelogram', ParallelogramHandler);
  registry.register('process2', Process2Handler);
  registry.register('providedRequiredInterface', ProvidedRequiredInterfaceHandler);
  registry.register('rectangle', RectangleHandler);
  registry.register('requiredInterface', RequiredInterfaceHandler);
  registry.register('requires', RequiresHandler);
  registry.register('rhombus', RhombusHandler);
  registry.register('singleArrow', SingleArrowHandler);
  registry.register('sortShape', SortShapeHandler);
  registry.register('sumEllipse', SumEllipseHandler);
  registry.register('switch', SwitchHandler);
  registry.register('tapeData', TapeDataHandler);
  registry.register('tee', TeeHandler);
  registry.register('transparent', TransparentHandler);
  registry.register('trapezoid', TrapezoidHandler);
  registry.register('triangle', TriangleHandler);
  registry.register('umlBoundary', UmlBoundaryHandler);
  registry.register('umlControl', UmlControlHandler);
  registry.register('umlDestroy', UmlDestroyHandler);
  registry.register('umlEntity', UmlEntityHandler);
  registry.register('umlState', UmlStateHandler);
  registry.register('xor', XorHandler);
}
