import type { ShapeRegistry } from '../../shape-registry.ts';
import { IosIBgMapHandler } from './i-bg-map.ts';
import { IosIBgStripedHandler } from './i-bg-striped.ts';
import { IosILocBarHandler } from './i-loc-bar.ts';
import { IosIPinHandler } from './i-pin.ts';
import { IosAnchorHandler } from './anchor.ts';
import { IosBottomButtonHandler } from './bottom-button.ts';
import { IosCheckboxHandler } from './checkbox.ts';
import { IosFancyRRectHandler } from './fancy-rrect.ts';
import { IosIAddIconHandler } from './i-add-icon.ts';
import { IosIAlertBoxHandler } from './i-alert-box.ts';
import { IosIAlphaListHandler } from './i-alpha-list.ts';
import { IosIAppBarHandler } from './i-app-bar.ts';
import { IosIArrowIconHandler } from './i-arrow-icon.ts';
import { IosIBgFlatHandler } from './i-bg-flat.ts';
import { IosIButtonHandler } from './i-button.ts';
import { IosIButtonBackHandler } from './i-button-back.ts';
import { IosIButtonFwHandler } from './i-button-fw.ts';
import { IosICallButtonsHandler } from './i-call-buttons.ts';
import { IosICallDialogHandler } from './i-call-dialog.ts';
import { IosICheckIconHandler } from './i-check-icon.ts';
import { IosICloudProgressBarHandler } from './i-cloud-progress-bar.ts';
import { IosIComboBoxHandler } from './i-combo-box.ts';
import { IosICopyHandler } from './i-copy.ts';
import { IosICopyAreaHandler } from './i-copy-area.ts';
import { IosIDeleteAppHandler } from './i-delete-app.ts';
import { IosIDeleteIconHandler } from './i-delete-icon.ts';
import { IosIDialogBoxHandler } from './i-dialog-box.ts';
import { IosIDirHandler } from './i-dir.ts';
import { IosIDownloadBarHandler } from './i-download-bar.ts';
import { IosIHomePageControlHandler } from './i-home-page-control.ts';
import { IosIIconGridHandler } from './i-icon-grid.ts';
import { IosIInfoIconHandler } from './i-info-icon.ts';
import { IosIKeybLettHandler } from './i-keyb-lett.ts';
import { IosIKeybNumbHandler } from './i-keyb-numb.ts';
import { IosIKeybSymbHandler } from './i-keyb-symb.ts';
import { IosILockButtonHandler } from './i-lock-button.ts';
import { IosIOnOffButtonHandler } from './i-on-off-button.ts';
import { IosIOptionHandler } from './i-option.ts';
import { IosIPadHandler } from './i-pad.ts';
import { IosIPageControlHandler } from './i-page-control.ts';
import { IosIPhoneHandler } from './i-phone.ts';
import { IosIPrevNextHandler } from './i-prev-next.ts';
import { IosIProgressBarHandler } from './i-progress-bar.ts';
import { IosIScreenNameBarHandler } from './i-screen-name-bar.ts';
import { IosISliderHandler } from './i-slider.ts';
import { IosISortFindIconHandler } from './i-sort-find-icon.ts';
import { IosITextInputHandler } from './i-text-input.ts';
import { IosITopBarHandler } from './i-top-bar.ts';
import { IosITopBar2Handler } from './i-top-bar2.ts';
import { IosITopBarLockedHandler } from './i-top-bar-locked.ts';
import { IosIURLBarHandler } from './i-urlbar.ts';
import { IosIVideoControlsHandler } from './i-video-controls.ts';
import { IosRrectHandler } from './rrect.ts';
import { IosTopButtonHandler } from './top-button.ts';
import { IosIButtonBarHandler } from './i-button-bar.ts';
import { IosICheckboxGroupHandler } from './i-checkbox-group.ts';
import { IosIHorButtonBarHandler } from './i-hor-button-bar.ts';
import { IosIRadioGroupHandler } from './i-radio-group.ts';

export function registerIosHandlers(registry: ShapeRegistry): void {
  registry.register('mxgraph.ios.iBgMap', IosIBgMapHandler);
  registry.register('mxgraph.ios.iBgStriped', IosIBgStripedHandler);
  registry.register('mxgraph.ios.iLocBar', IosILocBarHandler);
  registry.register('mxgraph.ios.iPin', IosIPinHandler);
  registry.register('mxgraph.ios.anchor', IosAnchorHandler);
  registry.register('mxgraph.ios.bottomButton', IosBottomButtonHandler);
  registry.register('mxgraph.ios.checkbox', IosCheckboxHandler);
  registry.register('mxgraph.ios.fancyRRect', IosFancyRRectHandler);
  registry.register('mxgraph.ios.iAddIcon', IosIAddIconHandler);
  registry.register('mxgraph.ios.iAlertBox', IosIAlertBoxHandler);
  registry.register('mxgraph.ios.iAlphaList', IosIAlphaListHandler);
  registry.register('mxgraph.ios.iAppBar', IosIAppBarHandler);
  registry.register('mxgraph.ios.iArrowIcon', IosIArrowIconHandler);
  registry.register('mxgraph.ios.iBgFlat', IosIBgFlatHandler);
  registry.register('mxgraph.ios.iButton', IosIButtonHandler);
  registry.register('mxgraph.ios.iButtonBack', IosIButtonBackHandler);
  registry.register('mxgraph.ios.iButtonFw', IosIButtonFwHandler);
  registry.register('mxgraph.ios.iCallButtons', IosICallButtonsHandler);
  registry.register('mxgraph.ios.iCallDialog', IosICallDialogHandler);
  registry.register('mxgraph.ios.iCheckIcon', IosICheckIconHandler);
  registry.register('mxgraph.ios.iCloudProgressBar', IosICloudProgressBarHandler);
  registry.register('mxgraph.ios.iComboBox', IosIComboBoxHandler);
  registry.register('mxgraph.ios.iCopy', IosICopyHandler);
  registry.register('mxgraph.ios.iCopyArea', IosICopyAreaHandler);
  registry.register('mxgraph.ios.iDeleteApp', IosIDeleteAppHandler);
  registry.register('mxgraph.ios.iDeleteIcon', IosIDeleteIconHandler);
  registry.register('mxgraph.ios.iDialogBox', IosIDialogBoxHandler);
  registry.register('mxgraph.ios.iDir', IosIDirHandler);
  registry.register('mxgraph.ios.iDownloadBar', IosIDownloadBarHandler);
  registry.register('mxgraph.ios.iHomePageControl', IosIHomePageControlHandler);
  registry.register('mxgraph.ios.iIconGrid', IosIIconGridHandler);
  registry.register('mxgraph.ios.iInfoIcon', IosIInfoIconHandler);
  registry.register('mxgraph.ios.iKeybLett', IosIKeybLettHandler);
  registry.register('mxgraph.ios.iKeybNumb', IosIKeybNumbHandler);
  registry.register('mxgraph.ios.iKeybSymb', IosIKeybSymbHandler);
  registry.register('mxgraph.ios.iLockButton', IosILockButtonHandler);
  registry.register('mxgraph.ios.iOnOffButton', IosIOnOffButtonHandler);
  registry.register('mxgraph.ios.iOption', IosIOptionHandler);
  registry.register('mxgraph.ios.iPad', IosIPadHandler);
  registry.register('mxgraph.ios.iPageControl', IosIPageControlHandler);
  registry.register('mxgraph.ios.iPhone', IosIPhoneHandler);
  registry.register('mxgraph.ios.iPrevNext', IosIPrevNextHandler);
  registry.register('mxgraph.ios.iProgressBar', IosIProgressBarHandler);
  registry.register('mxgraph.ios.iScreenNameBar', IosIScreenNameBarHandler);
  registry.register('mxgraph.ios.iSlider', IosISliderHandler);
  registry.register('mxgraph.ios.iSortFindIcon', IosISortFindIconHandler);
  registry.register('mxgraph.ios.iTextInput', IosITextInputHandler);
  registry.register('mxgraph.ios.iTopBar', IosITopBarHandler);
  registry.register('mxgraph.ios.iTopBar2', IosITopBar2Handler);
  registry.register('mxgraph.ios.iTopBarLocked', IosITopBarLockedHandler);
  registry.register('mxgraph.ios.iURLBar', IosIURLBarHandler);
  registry.register('mxgraph.ios.iVideoControls', IosIVideoControlsHandler);
  registry.register('mxgraph.ios.rrect', IosRrectHandler);
  registry.register('mxgraph.ios.topButton', IosTopButtonHandler);
  registry.register('mxgraph.ios.iButtonBar', IosIButtonBarHandler);
  registry.register('mxgraph.ios.iCheckboxGroup', IosICheckboxGroupHandler);
  registry.register('mxgraph.ios.iHorButtonBar', IosIHorButtonBarHandler);
  registry.register('mxgraph.ios.iRadioGroup', IosIRadioGroupHandler);
}
