import type { ShapeRegistry } from '../../shape-registry.ts';
import { ElectricalLogicGatesLogicGateHandler } from './logic-gate.ts';
import { ElectricalAbstractMux2Handler } from './mux2.ts';
import { ElectricalElectroMechanicalChangeoverContactSwitch2Handler } from './changeover-contact-switch2.ts';
import { ElectricalElectroMechanicalCircuitBreaker2Handler } from './circuit-breaker2.ts';
import { ElectricalElectroMechanicalDpdt3Handler } from './dpdt3.ts';
import { ElectricalElectroMechanicalDpst2Handler } from './dpst2.ts';
import { ElectricalElectroMechanicalFlowActuatedSwitchHandler } from './flow-actuated-switch.ts';
import { ElectricalElectroMechanicalFourPositionSwitch2Handler } from './four-position-switch2.ts';
import { ElectricalElectroMechanicalFuse2Handler } from './fuse2.ts';
import { ElectricalElectroMechanicalGasFlowActuatedSwitchHandler } from './gas-flow-actuated-switch.ts';
import { ElectricalElectroMechanicalInertiaSwitch2Handler } from './inertia-switch2.ts';
import { ElectricalElectroMechanicalIsolatorSwitch2Handler } from './isolator-switch2.ts';
import { ElectricalElectroMechanicalLimitSwitchHandler } from './limit-switch.ts';
import { ElectricalElectroMechanicalLimitSwitch2Handler } from './limit-switch2.ts';
import { ElectricalElectroMechanicalLiquidLevelActuatedSwitchHandler } from './liquid-level-actuated-switch.ts';
import { ElectricalElectroMechanicalLiquidLevelActuatedSwitch2Handler } from './liquid-level-actuated-switch2.ts';
import { ElectricalElectroMechanicalManualSwitch2Handler } from './manual-switch2.ts';
import { ElectricalElectroMechanicalPassingMakeContact2Handler } from './passing-make-contact2.ts';
import { ElectricalElectroMechanicalPressureActuatedSwitchHandler } from './pressure-actuated-switch.ts';
import { ElectricalElectroMechanicalProximityLimitSwitch2Handler } from './proximity-limit-switch2.ts';
import { ElectricalElectroMechanicalPushbuttonHandler } from './pushbutton.ts';
import { ElectricalElectroMechanicalPushbuttonBreak2Handler } from './pushbutton-break2.ts';
import { ElectricalElectroMechanicalPushbuttonMakeSwitch2Handler } from './pushbutton-make-switch2.ts';
import { ElectricalElectroMechanicalPushbuttonTwoCircuitSwitch2Handler } from './pushbutton-two-circuit-switch2.ts';
import { ElectricalElectroMechanicalReedSwitch2Handler } from './reed-switch2.ts';
import { ElectricalElectroMechanicalSafetyInterlockSwitchHandler } from './safety-interlock-switch.ts';
import { ElectricalElectroMechanicalSelectorSwitch3Position2Handler } from './selector-switch3position2.ts';
import { ElectricalElectroMechanicalSelectorSwitch4Position2Handler } from './selector-switch4position2.ts';
import { ElectricalElectroMechanicalSelectorSwitch6Position2Handler } from './selector-switch6position2.ts';
import { ElectricalElectroMechanicalShortingSelectorSwitch2Handler } from './shorting-selector-switch2.ts';
import { ElectricalElectroMechanicalSingleSwitchHandler } from './single-switch.ts';
import { ElectricalElectroMechanicalSpringReturn3Handler } from './spring-return3.ts';
import { ElectricalElectroMechanicalSwitchDisconnectorHandler } from './switch-disconnector.ts';
import { ElectricalElectroMechanicalTemperatureActuatedSwitchHandler } from './temperature-actuated-switch.ts';
import { ElectricalElectroMechanicalTemperatureSwitchHandler } from './temperature-switch.ts';
import { ElectricalElectroMechanicalThermostat2Handler } from './thermostat2.ts';
import { ElectricalElectroMechanicalThreePositionSwitch2Handler } from './three-position-switch2.ts';
import { ElectricalElectroMechanicalTimeDelaySwitchHandler } from './time-delay-switch.ts';
import { ElectricalElectroMechanicalTimeDelaySwitch2Handler } from './time-delay-switch2.ts';
import { ElectricalElectroMechanicalTwoPositionSwitch2Handler } from './two-position-switch2.ts';
import { ElectricalElectroMechanicalTwoWayContact2Handler } from './two-way-contact2.ts';
import { ElectricalElectroMechanicalTwoWaySwitchHandler } from './two-way-switch.ts';
import { ElectricalLogicGatesBuffer2Handler } from './buffer2.ts';
import { ElectricalLogicGatesDualInlineIcHandler } from './dual-inline-ic.ts';
import { ElectricalLogicGatesQfpIcHandler } from './qfp-ic.ts';
import { ElectricalMiscellaneousBatteryStackHandler } from './battery-stack.ts';
import { ElectricalSignalSourcesDcSource3V2Handler } from './dc-source-3-v2.ts';
import { ElectricalSignalSourcesSourceHandler } from './source.ts';
import { ElectricalTransmissionEightLineBusElbowHandler } from './eight-line-bus-elbow.ts';
import { ElectricalTransmissionFourLineBusElbowHandler } from './four-line-bus-elbow.ts';
import { ElectricalTransmissionStraightBusHandler } from './straight-bus.ts';
import { ElectricalTransmissionTestPointHandler } from './test-point.ts';
import { ElectricalTransmissionThreeLineBusElbowHandler } from './three-line-bus-elbow.ts';
import { ElectricalTransmissionTwoLineBusElbowHandler } from './two-line-bus-elbow.ts';

export const registerElectricalHandlers = (registry: ShapeRegistry): void => {
  registry.register('mxgraph.electrical.logic_gates.logic_gate', ElectricalLogicGatesLogicGateHandler);
  registry.register('mxgraph.electrical.abstract.mux2', ElectricalAbstractMux2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.changeoverContactSwitch2', ElectricalElectroMechanicalChangeoverContactSwitch2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.circuitBreaker2', ElectricalElectroMechanicalCircuitBreaker2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.dpdt3', ElectricalElectroMechanicalDpdt3Handler);
  registry.register('mxgraph.electrical.electro-mechanical.dpst2', ElectricalElectroMechanicalDpst2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.flowActuatedSwitch', ElectricalElectroMechanicalFlowActuatedSwitchHandler);
  registry.register('mxgraph.electrical.electro-mechanical.fourPositionSwitch2', ElectricalElectroMechanicalFourPositionSwitch2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.fuse2', ElectricalElectroMechanicalFuse2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.gasFlowActuatedSwitch', ElectricalElectroMechanicalGasFlowActuatedSwitchHandler);
  registry.register('mxgraph.electrical.electro-mechanical.inertiaSwitch2', ElectricalElectroMechanicalInertiaSwitch2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.isolatorSwitch2', ElectricalElectroMechanicalIsolatorSwitch2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.limitSwitch', ElectricalElectroMechanicalLimitSwitchHandler);
  registry.register('mxgraph.electrical.electro-mechanical.limitSwitch2', ElectricalElectroMechanicalLimitSwitch2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.liquidLevelActuatedSwitch', ElectricalElectroMechanicalLiquidLevelActuatedSwitchHandler);
  registry.register('mxgraph.electrical.electro-mechanical.liquidLevelActuatedSwitch2', ElectricalElectroMechanicalLiquidLevelActuatedSwitch2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.manualSwitch2', ElectricalElectroMechanicalManualSwitch2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.passingMakeContact2', ElectricalElectroMechanicalPassingMakeContact2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.pressureActuatedSwitch', ElectricalElectroMechanicalPressureActuatedSwitchHandler);
  registry.register('mxgraph.electrical.electro-mechanical.proximityLimitSwitch2', ElectricalElectroMechanicalProximityLimitSwitch2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.pushbutton', ElectricalElectroMechanicalPushbuttonHandler);
  registry.register('mxgraph.electrical.electro-mechanical.pushbuttonBreak2', ElectricalElectroMechanicalPushbuttonBreak2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.pushbuttonMakeSwitch2', ElectricalElectroMechanicalPushbuttonMakeSwitch2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.pushbuttonTwoCircuitSwitch2', ElectricalElectroMechanicalPushbuttonTwoCircuitSwitch2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.reedSwitch2', ElectricalElectroMechanicalReedSwitch2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.safetyInterlockSwitch', ElectricalElectroMechanicalSafetyInterlockSwitchHandler);
  registry.register('mxgraph.electrical.electro-mechanical.selectorSwitch3Position2', ElectricalElectroMechanicalSelectorSwitch3Position2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.selectorSwitch4Position2', ElectricalElectroMechanicalSelectorSwitch4Position2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.selectorSwitch6Position2', ElectricalElectroMechanicalSelectorSwitch6Position2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.shortingSelectorSwitch2', ElectricalElectroMechanicalShortingSelectorSwitch2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.singleSwitch', ElectricalElectroMechanicalSingleSwitchHandler);
  registry.register('mxgraph.electrical.electro-mechanical.springReturn3', ElectricalElectroMechanicalSpringReturn3Handler);
  registry.register('mxgraph.electrical.electro-mechanical.switchDisconnector', ElectricalElectroMechanicalSwitchDisconnectorHandler);
  registry.register('mxgraph.electrical.electro-mechanical.temperatureActuatedSwitch', ElectricalElectroMechanicalTemperatureActuatedSwitchHandler);
  registry.register('mxgraph.electrical.electro-mechanical.temperatureSwitch', ElectricalElectroMechanicalTemperatureSwitchHandler);
  registry.register('mxgraph.electrical.electro-mechanical.thermostat2', ElectricalElectroMechanicalThermostat2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.threePositionSwitch2', ElectricalElectroMechanicalThreePositionSwitch2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.timeDelaySwitch', ElectricalElectroMechanicalTimeDelaySwitchHandler);
  registry.register('mxgraph.electrical.electro-mechanical.timeDelaySwitch2', ElectricalElectroMechanicalTimeDelaySwitch2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.twoPositionSwitch2', ElectricalElectroMechanicalTwoPositionSwitch2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.twoWayContact2', ElectricalElectroMechanicalTwoWayContact2Handler);
  registry.register('mxgraph.electrical.electro-mechanical.twoWaySwitch', ElectricalElectroMechanicalTwoWaySwitchHandler);
  registry.register('mxgraph.electrical.logic_gates.buffer2', ElectricalLogicGatesBuffer2Handler);
  registry.register('mxgraph.electrical.logic_gates.dual_inline_ic', ElectricalLogicGatesDualInlineIcHandler);
  registry.register('mxgraph.electrical.logic_gates.qfp_ic', ElectricalLogicGatesQfpIcHandler);
  registry.register('mxgraph.electrical.miscellaneous.batteryStack', ElectricalMiscellaneousBatteryStackHandler);
  registry.register('mxgraph.electrical.signal_sources.dc_source_3_v2', ElectricalSignalSourcesDcSource3V2Handler);
  registry.register('mxgraph.electrical.signal_sources.source', ElectricalSignalSourcesSourceHandler);
  registry.register('mxgraph.electrical.transmission.eightLineBusElbow', ElectricalTransmissionEightLineBusElbowHandler);
  registry.register('mxgraph.electrical.transmission.fourLineBusElbow', ElectricalTransmissionFourLineBusElbowHandler);
  registry.register('mxgraph.electrical.transmission.straightBus', ElectricalTransmissionStraightBusHandler);
  registry.register('mxgraph.electrical.transmission.testPoint', ElectricalTransmissionTestPointHandler);
  registry.register('mxgraph.electrical.transmission.threeLineBusElbow', ElectricalTransmissionThreeLineBusElbowHandler);
  registry.register('mxgraph.electrical.transmission.twoLineBusElbow', ElectricalTransmissionTwoLineBusElbowHandler);
};
