import type { ShapeRegistry } from '../../shape-registry.ts';
import { BasicDropHandler } from './drop.ts';
import { BasicOctagonHandler } from './octagon.ts';
import { BasicPentagonHandler } from './pentagon.ts';
import { BasicPartConcEllipseHandler } from './part-conc-ellipse.ts';
import { BasicRectHandler } from './rect.ts';
import { BasicRectCalloutHandler } from './rect-callout.ts';
import { BasicRoundRectCalloutHandler } from './round-rect-callout.ts';
import { Basic4PointStar2Handler } from './4-point-star-2.ts';
import { BasicAcuteTriangleHandler } from './acute-triangle.ts';
import { BasicArcHandler } from './arc.ts';
import { BasicBendingArchHandler } from './bending-arch.ts';
import { BasicButtonHandler } from './button.ts';
import { BasicCone2Handler } from './cone2.ts';
import { BasicCornerRoundRectHandler } from './corner-round-rect.ts';
import { BasicCross2Handler } from './cross2.ts';
import { BasicDiagRoundRectHandler } from './diag-round-rect.ts';
import { BasicDiagSnipRectHandler } from './diag-snip-rect.ts';
import { BasicDiagStripeHandler } from './diag-stripe.ts';
import { BasicDonutHandler } from './donut.ts';
import { BasicFrameHandler } from './frame.ts';
import { BasicFrameCornerHandler } from './frame-corner.ts';
import { BasicIsocubeHandler } from './isocube.ts';
import { BasicLayeredRectHandler } from './layered-rect.ts';
import { BasicNumberedEntryVertHandler } from './numbered-entry-vert.ts';
import { BasicObtuseTriangleHandler } from './obtuse-triangle.ts';
import { BasicOctagon2Handler } from './octagon2.ts';
import { BasicPatternFillRectHandler } from './pattern-fill-rect.ts';
import { BasicPieHandler } from './pie.ts';
import { BasicPlaqueHandler } from './plaque.ts';
import { BasicPlaqueFrameHandler } from './plaque-frame.ts';
import { BasicPolygonHandler } from './polygon.ts';
import { BasicPyramidHandler } from './pyramid.ts';
import { BasicRoundedFrameHandler } from './rounded-frame.ts';
import { BasicShadedButtonHandler } from './shaded-button.ts';
import { BasicThreeCornerRoundRectHandler } from './three-corner-round-rect.ts';
import { BasicWave2Handler } from './wave2.ts';

export function registerBasicHandlers(registry: ShapeRegistry): void {
  registry.register('mxgraph.basic.drop', BasicDropHandler);
  registry.register('mxgraph.basic.octagon', BasicOctagonHandler);
  registry.register('mxgraph.basic.pentagon', BasicPentagonHandler);
  registry.register('mxgraph.basic.partConcEllipse', BasicPartConcEllipseHandler);
  registry.register('mxgraph.basic.rect', BasicRectHandler);
  registry.register('mxgraph.basic.rectCallout', BasicRectCalloutHandler);
  registry.register('mxgraph.basic.roundRectCallout', BasicRoundRectCalloutHandler);
  registry.register('mxgraph.basic.4_point_star_2', Basic4PointStar2Handler);
  registry.register('mxgraph.basic.acute_triangle', BasicAcuteTriangleHandler);
  registry.register('mxgraph.basic.arc', BasicArcHandler);
  registry.register('mxgraph.basic.bendingArch', BasicBendingArchHandler);
  registry.register('mxgraph.basic.button', BasicButtonHandler);
  registry.register('mxgraph.basic.cone2', BasicCone2Handler);
  registry.register('mxgraph.basic.corner_round_rect', BasicCornerRoundRectHandler);
  registry.register('mxgraph.basic.cross2', BasicCross2Handler);
  registry.register('mxgraph.basic.diag_round_rect', BasicDiagRoundRectHandler);
  registry.register('mxgraph.basic.diag_snip_rect', BasicDiagSnipRectHandler);
  registry.register('mxgraph.basic.diag_stripe', BasicDiagStripeHandler);
  registry.register('mxgraph.basic.donut', BasicDonutHandler);
  registry.register('mxgraph.basic.frame', BasicFrameHandler);
  registry.register('mxgraph.basic.frame_corner', BasicFrameCornerHandler);
  registry.register('mxgraph.basic.isocube', BasicIsocubeHandler);
  registry.register('mxgraph.basic.layered_rect', BasicLayeredRectHandler);
  registry.register('mxgraph.basic.numberedEntryVert', BasicNumberedEntryVertHandler);
  registry.register('mxgraph.basic.obtuse_triangle', BasicObtuseTriangleHandler);
  registry.register('mxgraph.basic.octagon2', BasicOctagon2Handler);
  registry.register('mxgraph.basic.patternFillRect', BasicPatternFillRectHandler);
  registry.register('mxgraph.basic.pie', BasicPieHandler);
  registry.register('mxgraph.basic.plaque', BasicPlaqueHandler);
  registry.register('mxgraph.basic.plaque_frame', BasicPlaqueFrameHandler);
  registry.register('mxgraph.basic.polygon', BasicPolygonHandler);
  registry.register('mxgraph.basic.pyramid', BasicPyramidHandler);
  registry.register('mxgraph.basic.rounded_frame', BasicRoundedFrameHandler);
  registry.register('mxgraph.basic.shaded_button', BasicShadedButtonHandler);
  registry.register('mxgraph.basic.three_corner_round_rect', BasicThreeCornerRoundRectHandler);
  registry.register('mxgraph.basic.wave2', BasicWave2Handler);
}
