import type { ShapeRegistry } from '../../shape-registry.ts';
import { MockupBrowserWindowHandler } from './browser-window.ts';
import { MockupButtonHandler } from './button.ts';
import { MockupCheckboxGroupHandler } from './checkbox-group.ts';
import { MockupComboBoxHandler } from './combo-box.ts';
import { MockupColumnChartHandler } from './column-chart.ts';
import { MockupIconGridHandler } from './icon-grid.ts';
import { MockupPieChartHandler } from './pie-chart.ts';
import { MockupSearchBoxHandler } from './search-box.ts';
import { MockupSimpleIconHandler } from './simple-icon.ts';
import { MockupSpinnerHandler } from './spinner.ts';
import { MockupVideoPlayerHandler } from './video-player.ts';
import { MockupWindowHandler } from './window.ts';
import { MockupNavigationAnchorHandler as MockupContainersAnchorHandler } from './anchor.ts';
import { MockupMarkupLineHandler } from './line.ts';
import { MockupMiscRatingHandler } from './rating.ts';
import { MockupNavigationAnchorHandler as MockupAnchorHandler } from './anchor.ts';
import { MockupBottomButtonHandler } from './bottom-button.ts';
import { MockupButtonsMultiButtonHandler } from './multi-button.ts';
import { MockupButtonsOnOffButtonHandler } from './on-off-button.ts';
import { MockupContainersAlertBoxHandler } from './alert-box.ts';
import { MockupContainersGroupHandler } from './group.ts';
import { MockupLeftButtonHandler as MockupContainersLeftButtonHandler } from './left-button.ts';
import { MockupContainersMarginRectHandler } from './margin-rect.ts';
import { MockupContainersMarginRect2Handler } from './margin-rect2.ts';
import { MockupTextRrectHandler as MockupContainersRrectHandler } from './rrect.ts';
import { MockupTopButtonHandler as MockupContainersTopButtonHandler } from './top-button.ts';
import { MockupContainersUserFemaleHandler } from './user-female.ts';
import { MockupContainersUserMaleHandler } from './user-male.ts';
import { MockupNavigationAnchorHandler as MockupFormsAnchorHandler } from './anchor.ts';
import { MockupFormsCalendarHandler } from './calendar.ts';
import { MockupFormsCheckboxHandler } from './checkbox.ts';
import { MockupFormsColorPickerHandler } from './color-picker.ts';
import { MockupFormsEmailFormHandler } from './email-form.ts';
import { MockupFormsHorSliderHandler } from './hor-slider.ts';
import { MockupFormsPwFieldHandler } from './pw-field.ts';
import { MockupTextRrectHandler as MockupFormsRrectHandler } from './rrect.ts';
import { MockupFormsSplitterHandler } from './splitter.ts';
import { MockupFormsURectHandler } from './u-rect.ts';
import { MockupNavigationAnchorHandler as MockupGraphicsAnchorHandler } from './anchor.ts';
import { MockupGraphicsBarChartHandler } from './bar-chart.ts';
import { MockupGraphicsBubbleChartHandler } from './bubble-chart.ts';
import { MockupGraphicsGanttChartHandler } from './gantt-chart.ts';
import { MockupGraphicsGaugeHandler } from './gauge.ts';
import { MockupGraphicsLineChartHandler } from './line-chart.ts';
import { MockupGraphicsPlotChartHandler } from './plot-chart.ts';
import { MockupTextRrectHandler as MockupGraphicsRrectHandler } from './rrect.ts';
import { MockupLeftButtonHandler } from './left-button.ts';
import { MockupMarkupCurlyBraceHandler } from './curly-brace.ts';
import { MockupMarkupRedXHandler } from './red-x.ts';
import { MockupMarkupScratchOutHandler } from './scratch-out.ts';
import { MockupNavigationAnchorHandler as MockupMiscAnchorHandler } from './anchor.ts';
import { MockupMiscCopyrightIconHandler } from './copyright-icon.ts';
import { MockupMiscEditIconHandler } from './edit-icon.ts';
import { MockupMiscMail2Handler } from './mail2.ts';
import { MockupMiscPinHandler } from './pin.ts';
import { MockupMiscPlaybackControlsHandler } from './playback-controls.ts';
import { MockupMiscPrintIconHandler } from './print-icon.ts';
import { MockupMiscProgressBarHandler } from './progress-bar.ts';
import { MockupMiscRegisteredIconHandler } from './registered-icon.ts';
import { MockupMiscRevisionTableHandler } from './revision-table.ts';
import { MockupTextRrectHandler as MockupMiscRrectHandler } from './rrect.ts';
import { MockupMiscRulerHandler } from './ruler.ts';
import { MockupMiscRuler2Handler } from './ruler2.ts';
import { MockupMiscShareIconHandler } from './share-icon.ts';
import { MockupMiscShoppingCartHandler } from './shopping-cart.ts';
import { MockupMiscStatusBarHandler } from './status-bar.ts';
import { MockupMiscTrashcanIconHandler } from './trashcan-icon.ts';
import { MockupMiscVolumeIconHandler } from './volume-icon.ts';
import { MockupMiscVolumeSliderHandler } from './volume-slider.ts';
import { MockupNavigationAnchorHandler } from './anchor.ts';
import { MockupNavigationCoverFlowHandler } from './cover-flow.ts';
import { MockupNavigationMapNavigatorHandler } from './map-navigator.ts';
import { MockupNavigationPageControlHandler } from './page-control.ts';
import { MockupNavigationScrollBarHandler } from './scroll-bar.ts';
import { MockupRightButtonHandler } from './right-button.ts';
import { MockupTextBulletedListHandler } from './bulleted-list.ts';
import { MockupTextCaptchaHandler } from './captcha.ts';
import { MockupTextRrectHandler } from './rrect.ts';
import { MockupTextStickyNoteHandler } from './sticky-note.ts';
import { MockupTextStickyNote2Handler } from './sticky-note2.ts';
import { MockupTextTextBoxHandler } from './text-box.ts';
import { MockupTopButtonHandler } from './top-button.ts';
import { MockupButtonsHorButtonBarHandler } from './hor-button-bar.ts';
import { MockupContainersAccordionHandler } from './accordion.ts';
import { MockupContainersHorTabBarHandler } from './hor-tab-bar.ts';
import { MockupContainersVerTabBarHandler } from './ver-tab-bar.ts';
import { MockupFormsListBoxHandler } from './list-box.ts';
import { MockupFormsMenuBarHandler } from './menu-bar.ts';
import { MockupFormsRadioGroupHandler } from './radio-group.ts';
import { MockupFormsSignInHandler } from './sign-in.ts';
import { MockupFormsWedgeBarHandler } from './wedge-bar.ts';
import { MockupNavigationBreadcrumbHandler } from './breadcrumb.ts';
import { MockupNavigationPaginationHandler } from './pagination.ts';
import { MockupNavigationStepBarHandler } from './step-bar.ts';
import { MockupTextAlphanumericHandler } from './alphanumeric.ts';
import { MockupTextCalloutHandler } from './callout.ts';
import { MockupTextLinkHandler } from './link.ts';
import { MockupTextLinkBarHandler } from './link-bar.ts';
import { MockupButtonsVerButtonBarHandler } from './ver-button-bar.ts';

export function registerMockupHandlers(registry: ShapeRegistry): void {
	registry.register('mxgraph.mockup.forms.comboBox', MockupComboBoxHandler);
	registry.register('mxgraph.mockup.forms.checkboxGroup', MockupCheckboxGroupHandler);
	registry.register('mxgraph.mockup.forms.searchBox', MockupSearchBoxHandler);
	registry.register('mxgraph.mockup.forms.spinner', MockupSpinnerHandler);
	registry.register('mxgraph.mockup.buttons.button', MockupButtonHandler);
	registry.register('mxgraph.mockup.containers.browserWindow', MockupBrowserWindowHandler);
	registry.register('mxgraph.mockup.containers.videoPlayer', MockupVideoPlayerHandler);
	registry.register('mxgraph.mockup.containers.window', MockupWindowHandler);
	registry.register('mxgraph.mockup.graphics.columnChart', MockupColumnChartHandler);
	registry.register('mxgraph.mockup.graphics.iconGrid', MockupIconGridHandler);
	registry.register('mxgraph.mockup.graphics.pieChart', MockupPieChartHandler);
	registry.register('mxgraph.mockup.graphics.simpleIcon', MockupSimpleIconHandler);
  registry.register('mxgraph.mockup.containers.anchor', MockupContainersAnchorHandler);
  registry.register('mxgraph.mockup.markup.line', MockupMarkupLineHandler);
  registry.register('mxgraph.mockup.misc.rating', MockupMiscRatingHandler);
  registry.register('mxgraph.mockup.anchor', MockupAnchorHandler);
  registry.register('mxgraph.mockup.bottomButton', MockupBottomButtonHandler);
  registry.register('mxgraph.mockup.buttons.multiButton', MockupButtonsMultiButtonHandler);
  registry.register('mxgraph.mockup.buttons.onOffButton', MockupButtonsOnOffButtonHandler);
  registry.register('mxgraph.mockup.containers.alertBox', MockupContainersAlertBoxHandler);
  registry.register('mxgraph.mockup.containers.group', MockupContainersGroupHandler);
  registry.register('mxgraph.mockup.containers.leftButton', MockupContainersLeftButtonHandler);
  registry.register('mxgraph.mockup.containers.marginRect', MockupContainersMarginRectHandler);
  registry.register('mxgraph.mockup.containers.marginRect2', MockupContainersMarginRect2Handler);
  registry.register('mxgraph.mockup.containers.rrect', MockupContainersRrectHandler);
  registry.register('mxgraph.mockup.containers.topButton', MockupContainersTopButtonHandler);
  registry.register('mxgraph.mockup.containers.userFemale', MockupContainersUserFemaleHandler);
  registry.register('mxgraph.mockup.containers.userMale', MockupContainersUserMaleHandler);
  registry.register('mxgraph.mockup.forms.anchor', MockupFormsAnchorHandler);
  registry.register('mxgraph.mockup.forms.calendar', MockupFormsCalendarHandler);
  registry.register('mxgraph.mockup.forms.checkbox', MockupFormsCheckboxHandler);
  registry.register('mxgraph.mockup.forms.colorPicker', MockupFormsColorPickerHandler);
  registry.register('mxgraph.mockup.forms.emailForm', MockupFormsEmailFormHandler);
  registry.register('mxgraph.mockup.forms.horSlider', MockupFormsHorSliderHandler);
  registry.register('mxgraph.mockup.forms.pwField', MockupFormsPwFieldHandler);
  registry.register('mxgraph.mockup.forms.rrect', MockupFormsRrectHandler);
  registry.register('mxgraph.mockup.forms.splitter', MockupFormsSplitterHandler);
  registry.register('mxgraph.mockup.forms.uRect', MockupFormsURectHandler);
  registry.register('mxgraph.mockup.graphics.anchor', MockupGraphicsAnchorHandler);
  registry.register('mxgraph.mockup.graphics.barChart', MockupGraphicsBarChartHandler);
  registry.register('mxgraph.mockup.graphics.bubbleChart', MockupGraphicsBubbleChartHandler);
  registry.register('mxgraph.mockup.graphics.ganttChart', MockupGraphicsGanttChartHandler);
  registry.register('mxgraph.mockup.graphics.gauge', MockupGraphicsGaugeHandler);
  registry.register('mxgraph.mockup.graphics.lineChart', MockupGraphicsLineChartHandler);
  registry.register('mxgraph.mockup.graphics.plotChart', MockupGraphicsPlotChartHandler);
  registry.register('mxgraph.mockup.graphics.rrect', MockupGraphicsRrectHandler);
  registry.register('mxgraph.mockup.leftButton', MockupLeftButtonHandler);
  registry.register('mxgraph.mockup.markup.curlyBrace', MockupMarkupCurlyBraceHandler);
  registry.register('mxgraph.mockup.markup.redX', MockupMarkupRedXHandler);
  registry.register('mxgraph.mockup.markup.scratchOut', MockupMarkupScratchOutHandler);
  registry.register('mxgraph.mockup.misc.anchor', MockupMiscAnchorHandler);
  registry.register('mxgraph.mockup.misc.copyrightIcon', MockupMiscCopyrightIconHandler);
  registry.register('mxgraph.mockup.misc.editIcon', MockupMiscEditIconHandler);
  registry.register('mxgraph.mockup.misc.mail2', MockupMiscMail2Handler);
  registry.register('mxgraph.mockup.misc.pin', MockupMiscPinHandler);
  registry.register('mxgraph.mockup.misc.playbackControls', MockupMiscPlaybackControlsHandler);
  registry.register('mxgraph.mockup.misc.printIcon', MockupMiscPrintIconHandler);
  registry.register('mxgraph.mockup.misc.progressBar', MockupMiscProgressBarHandler);
  registry.register('mxgraph.mockup.misc.registeredIcon', MockupMiscRegisteredIconHandler);
  registry.register('mxgraph.mockup.misc.revisionTable', MockupMiscRevisionTableHandler);
  registry.register('mxgraph.mockup.misc.rrect', MockupMiscRrectHandler);
  registry.register('mxgraph.mockup.misc.ruler', MockupMiscRulerHandler);
  registry.register('mxgraph.mockup.misc.ruler2', MockupMiscRuler2Handler);
  registry.register('mxgraph.mockup.misc.shareIcon', MockupMiscShareIconHandler);
  registry.register('mxgraph.mockup.misc.shoppingCart', MockupMiscShoppingCartHandler);
  registry.register('mxgraph.mockup.misc.statusBar', MockupMiscStatusBarHandler);
  registry.register('mxgraph.mockup.misc.trashcanIcon', MockupMiscTrashcanIconHandler);
  registry.register('mxgraph.mockup.misc.volumeIcon', MockupMiscVolumeIconHandler);
  registry.register('mxgraph.mockup.misc.volumeSlider', MockupMiscVolumeSliderHandler);
  registry.register('mxgraph.mockup.navigation.anchor', MockupNavigationAnchorHandler);
  registry.register('mxgraph.mockup.navigation.coverFlow', MockupNavigationCoverFlowHandler);
  registry.register('mxgraph.mockup.navigation.mapNavigator', MockupNavigationMapNavigatorHandler);
  registry.register('mxgraph.mockup.navigation.pageControl', MockupNavigationPageControlHandler);
  registry.register('mxgraph.mockup.navigation.scrollBar', MockupNavigationScrollBarHandler);
  registry.register('mxgraph.mockup.rightButton', MockupRightButtonHandler);
  registry.register('mxgraph.mockup.text.bulletedList', MockupTextBulletedListHandler);
  registry.register('mxgraph.mockup.text.captcha', MockupTextCaptchaHandler);
  registry.register('mxgraph.mockup.text.rrect', MockupTextRrectHandler);
  registry.register('mxgraph.mockup.text.stickyNote', MockupTextStickyNoteHandler);
  registry.register('mxgraph.mockup.text.stickyNote2', MockupTextStickyNote2Handler);
  registry.register('mxgraph.mockup.text.textBox', MockupTextTextBoxHandler);
  registry.register('mxgraph.mockup.topButton', MockupTopButtonHandler);
  registry.register('mxgraph.mockup.buttons.horButtonBar', MockupButtonsHorButtonBarHandler);
  registry.register('mxgraph.mockup.containers.accordion', MockupContainersAccordionHandler);
  registry.register('mxgraph.mockup.containers.horTabBar', MockupContainersHorTabBarHandler);
  registry.register('mxgraph.mockup.containers.verTabBar', MockupContainersVerTabBarHandler);
  registry.register('mxgraph.mockup.forms.listBox', MockupFormsListBoxHandler);
  registry.register('mxgraph.mockup.forms.menuBar', MockupFormsMenuBarHandler);
  registry.register('mxgraph.mockup.forms.radioGroup', MockupFormsRadioGroupHandler);
  registry.register('mxgraph.mockup.forms.signIn', MockupFormsSignInHandler);
  registry.register('mxgraph.mockup.forms.wedgeBar', MockupFormsWedgeBarHandler);
  registry.register('mxgraph.mockup.navigation.breadcrumb', MockupNavigationBreadcrumbHandler);
  registry.register('mxgraph.mockup.navigation.pagination', MockupNavigationPaginationHandler);
  registry.register('mxgraph.mockup.navigation.stepBar', MockupNavigationStepBarHandler);
  registry.register('mxgraph.mockup.text.alphanumeric', MockupTextAlphanumericHandler);
  registry.register('mxgraph.mockup.text.callout', MockupTextCalloutHandler);
  registry.register('mxgraph.mockup.text.link', MockupTextLinkHandler);
  registry.register('mxgraph.mockup.text.linkBar', MockupTextLinkBarHandler);
  registry.register('mxgraph.mockup.buttons.verButtonBar', MockupButtonsVerButtonBarHandler);
}